# Generated by Django 5.1 on 2024-09-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_profile_avt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avt',
            field=models.ImageField(default='img/default-user.png', upload_to='img'),
        ),
    ]
