# Generated by Django 5.1 on 2024-09-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_post_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ageband',
            field=models.CharField(choices=[('Ẩn', 'Ẩn'), ('18-30', '18-30'), ('31-45', '31-45'), ('46-65', '41-65'), ('65+', '65+')], default='Ẩn', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img/default-img.jpg', upload_to='img'),
        ),
    ]
