# Generated by Django 5.1 on 2024-09-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_profile_ageband_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ageband',
            field=models.CharField(choices=[('Ẩn', 'Ẩn'), ('18-30', '18-30'), ('31-45', '31-45'), ('46-65', '46-65'), ('65+', '65+')], default='Ẩn', max_length=10),
        ),
    ]
