# Generated by Django 5.1 on 2024-09-17 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_profile_ageband'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ageband',
            new_name='age_band',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_topic', to='myapp.topic')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_section', to='myapp.section'),
        ),
    ]
