# Generated by Django 5.1 on 2024-09-17 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_rename_ageband_profile_age_band_remove_post_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_section', to='myapp.section'),
        ),
    ]
