# Generated by Django 5.1 on 2024-09-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_post_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='modified',
        ),
        migrations.AddField(
            model_name='post',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
