# Generated by Django 5.1 on 2024-09-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_post_modified_post_end_date_post_is_confirmed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_deleted',
            new_name='is_approved',
        ),
    ]
