# Generated by Django 5.1 on 2024-09-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_rename_is_deleted_post_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Chờ duyệt', 'Chờ duyệt'), ('Chờ edit', 'Chờ edit'), ('Chờ đăng', 'Chờ đăng'), ('Đã đăng', 'Đã đăng')], default='Chờ duyệt', max_length=20),
        ),
    ]
