# Generated by Django 5.1 on 2024-09-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_post_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='start_date',
        ),
        migrations.AddField(
            model_name='post',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
