# Generated by Django 5.1 on 2024-09-22 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_rename_update_at_post_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Chờ gửi', 'Chờ gửi'), ('Chờ duyệt', 'Chờ duyệt'), ('Từ chối', 'Từ chối'), ('Chờ sửa', 'Chờ sửa'), ('Chờ đăng', 'Chờ đăng'), ('Không đăng', 'Không đăng'), ('Đã đăng', 'Đã đăng')], default='Chờ gửi', max_length=20),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='myapp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
